Make ocean.core.Traits : isTypedef, StripTypedef useful in D2
sociomantic-tsunami/ocean pull request #124
Opened 2017-05-22 12:16 UTC by mathias-lang-sociomantic

It's been a common problem during porting that some meta code needed to special-case Typedef but couldn't.
The code was originally trying to ensure that no typedef special casing happened, but it proved impossible in some cases,
which led to libraries / utilities implementing their own StripTypedef / IsTypedef (e.g. the Formatter).
This fixes the problem at the root, by exposing same behavior between D1 and D2.

CC @mihails-strasuns-sociomantic

2017-05-26 12:06 UTC, mihails-strasuns-sociomantic commented
If you insist on going this path I would like to make it more generic via some convention so that arbitrary struct can enable typedef-like treatment. Something like `is(S.TypedefBaseType) && is(typeof({ S.TypedefBaseType base = S.init; }))`

2017-05-31 20:02 UTC, mathias-lang-sociomantic commented
> If you insist on going this path I would like to make it more generic via some convention so that arbitrary struct can enable typedef-like treatment.

Do we really want to go this way ? My intent is not to promote `typedef`. This feature was killed. The suggested replacement does not cover all the use case there is, because `typedef` is a way to subtype, but `alias this` is not. It does 95% of the job, but *cannot* do all of it.
However, we *do* rely on this feature in our code. With D2 abilities we might be able to transition to a more lax approach, but for the moment we need one way to emulate `Typedef`, and that's it. I just found another case where typedef has to be handled explicitly.

2017-05-31 22:24 UTC, mathias-lang-sociomantic commented
My previous patch was quite incomplete, and there's some code which should have broke which did not.
In any case, I added several more fixes.

2017-06-01 07:30 UTC, mihails-strasuns-sociomantic commented
>  My intent is not to promote typedef. This feature was killed.

It is exactly the reasoning of my proposal. I don't want to introduce trait which sole purpose is to support legacy concept, it only introduce more technical debt in any code that uses it. Instead it would be much more sustainable to introduce concept saying "A is supertype of A.Type and is implicitly convertible to A.Type" and implement all generic algorithms in these terms.

For example, I would totally like formatter to print `Contiguous!(S)` structs same as `S` in D2 when `alias ptr this` will be introduced. With my proposal it would be simply a matter of defining `alias SubType = S;`, with yours it would require explicit formatter support or wrapper `toString` that simply forwards to `ptr.toString()` - and add more such workaround for each purpose that treats `typedef` specially right now. I don't think it scales at all.

2017-06-01 12:04 UTC, mathias-lang-sociomantic commented
```diff
diff --git a/src/ocean/core/Traits.d b/src/ocean/core/Traits.d
index 1419fe1..7e01e23 100644
--- a/src/ocean/core/Traits.d
+++ b/src/ocean/core/Traits.d
@@ -912,7 +912,7 @@ version (D_Version2)
     public template StripTypedef (T)
     {
         static if (isTypedef!(T))
-            alias typeof(T.value) StripTypedef;
+            alias T.TypedefBaseType StripTypedef;
         else
             alias T StripTypedef;
     }
diff --git a/src/ocean/transition.d b/src/ocean/transition.d
index c8d223f..f2607a4 100644
--- a/src/ocean/transition.d
+++ b/src/ocean/transition.d
@@ -101,6 +101,7 @@ template Typedef(T, istring name, T initval)
                 ("static struct " ~ name ~
                 "{ " ~
                 "alias IsTypedef = void;" ~
+                "alias TypedefBaseType = " ~ T.stringof ~ ";" ~
                 T.stringof ~ " value = " ~ initval.stringof ~ ";" ~
                 "alias value this;" ~
                 "this(" ~ T.stringof ~ " rhs) { this.value = rhs; }" ~
@@ -127,6 +128,7 @@ template Typedef(T, istring name)
                 ("static struct " ~ name ~
                 "{ " ~
                 "alias IsTypedef = void;" ~
+                "alias TypedefBaseType = " ~ T.stringof ~ ";" ~
                 T.stringof ~ " value; " ~
                 "alias value this;" ~
                 "this(" ~ T.stringof ~ " rhs) { this.value = rhs; }" ~
```

2017-06-01 13:34 UTC, mathias-lang-sociomantic commented
I've no idea why the coverage seems to go down. It points to `Convert.d` for example, but I've removed an unused branch. But since the code is not compiled in, DMD doesn't care...

2017-06-01 18:42 UTC, mihails-strasuns-sociomantic commented
It even reports some unchanged module. I wonder who is to blame here - dmd or codecov x_X

2017-06-02 10:25 UTC, mathias-lang-sociomantic commented
Well this module is a random engine, so it might be neither of them :)

2017-06-06 14:29 UTC, mathias-lang-sociomantic commented
Ping @mihails-strasuns-sociomantic

2017-06-07 07:47 UTC, mihails-strasuns-sociomantic requested changes
Sorry for long response, had some wild medical adventures, now catching back.

Sadly, this PR still works in "typedef" terms and this is not acceptable (see one specific line comment for issue example). My proposal was to do something conceptually different:

1) Deprecate `isTypedef` / `StripTypedef` completely
2) Renamed mixed in field in `Typedef` to `BaseType`
3) Introduce new `hasBaseType` and `toBaseType` functions with implementation similar to the one for `StripTypedef` in the current PR
4) Evaluate each current usage place of `isTypedef` individually, checking if it indeed to makes sense to replace one type with possibly completely different type in that context. Among places highlighted by this PR, formatter definitely can and should do it, but serializer is a no go.

2017-06-07 07:47 UTC, mihails-strasuns-sociomantic commented on src/ocean/io/serialize/StructSerializer.d
> +                    serializer.serialize(data, cast(StripTypedef!(T))(field),
So this is exactly why I don't want to allow silent `StripTypedef` application to D2 structs. Serializer must not reduce an entity to the base type but serialize it as actual struct. For current `Typedef` implementation ABI is compatible as deserialization will not show any immediate issues but it is an undefined behaviour time bomb.

2017-06-07 09:28 UTC, mathias-lang-sociomantic commented on src/ocean/io/serialize/StructSerializer.d
> +                    serializer.serialize(data, cast(StripTypedef!(T))(field),
ABI **has** to be compatible. If not, D2 apps won't be able to deserialize profiles that contain `typedef` which were serialized in D1.

2017-06-07 09:41 UTC, mihails-strasuns-sociomantic commented on src/ocean/io/serialize/StructSerializer.d
> +                    serializer.serialize(data, cast(StripTypedef!(T))(field),
Yes, but intended usage of this feature is not limited to legacy `Typedef`. As I have mentioned previously, after we drop D1 support in ocean I want to modify `Contiguous` to say `ref S value(); alias value this; alias BaseType = S;` and get it processed by `Formatter` like `S` for free. There are many more places where one may want well-defined subtyping relation but if your utilities operate in typedef terms, it becomes applicable only for typedef-like entities.

2017-06-07 09:45 UTC, mihails-strasuns-sociomantic commented on src/ocean/io/serialize/StructSerializer.d
> +                    serializer.serialize(data, cast(StripTypedef!(T))(field),
To re-iterate previous context - I don't want any non-deprecate symbols in ocean that support typedef as a special concept in D2 mode. That thing is gone and we should focus more on future proof concepts than on legacy support.

2017-06-07 09:46 UTC, mihails-strasuns-sociomantic commented on src/ocean/core/Traits.d
> +                StripTypedef!(T[0]), T[1 .. $]);
Here `StripTypedef` is not needed in D2 either, the field will be processed as any struct field anyway.

2017-06-07 09:47 UTC, mihails-strasuns-sociomantic commented
So I have just checked again and looks like formatter is the only piece of ocean which uses `StripTypedef` legitimately here.

2017-06-07 09:50 UTC, mathias-lang-sociomantic commented
> So I have just checked again and looks like formatter is the only piece of ocean which uses StripTypedef legitimately here.

https://github.com/sociomantic-tsunami/ocean/pull/138

2017-06-07 10:10 UTC, mihails-strasuns-sociomantic commented
"here" means "in this PR" - #138 is much more tricky case and I would discuss it separately (using `StripTypedef` there is *wrong* but necessary to maintain comptibility between D1 and D2 file formats)

2017-06-08 15:31 UTC, mathias-lang-sociomantic commented
Closing as per lack of agreement and since #138 is now using its own copy of `IsTypedef`  / `DropTypedef`.

2017-06-08 15:31 UTC, closed without merging