Fix TypeId with Typedef and improve code coverage
sociomantic-tsunami/ocean pull request #138
Opened 2017-05-31 22:30 UTC by mathias-lang-sociomantic

This is based on #124 

`TypeId` was not tested, and was in fact not working with `Typedef` in D2.
As it is used by the mapserializer, it caused applications using maps to fail to load their maps, as the hash was different. This should fix it.

2017-05-31 23:07 UTC, mathias-lang-sociomantic commented
Tested with the app, it works

2017-06-07 06:44 UTC, mihails-strasuns-sociomantic requested changes

2017-06-07 06:44 UTC, mihails-strasuns-sociomantic commented on relnotes/typedef-no-more.feature.md
> +* `ocean.core.Traits : isTypedef, StripTypedef`
Release notes from other pr, missing rebase?

2017-06-07 09:29 UTC, mathias-lang-sociomantic commented on relnotes/typedef-no-more.feature.md
> +* `ocean.core.Traits : isTypedef, StripTypedef`
> This is based on #124

2017-06-07 09:35 UTC, mihails-strasuns-sociomantic commented on relnotes/typedef-no-more.feature.md
> +* `ocean.core.Traits : isTypedef, StripTypedef`
Sorry, missed that one :)

2017-06-08 11:17 UTC, mathias-lang-sociomantic commented
Changed it to not rely on #124
Also changed it to target `v2.7.x`

2017-06-08 15:35 UTC, mihails-strasuns-sociomantic approved these changes
Merging now to unblock fixing downstream while long-term approach is discussed

2017-06-08 15:36 UTC, merged