Reduce dependency on old loggers, move some functionality in ILogger
sociomantic-tsunami/ocean pull request #172
Opened 2017-07-03 19:12 UTC by mathias-lang-sociomantic

I am currently working on deprecating the old loggers. I have a set of patches (almost) working on top of v3.x.x, but some of the changes can be done in v2.x.x, so I cherry-picked them here.
The 3rd patch (Trivial: Fix ILogger code style and comments) might create conflicts because the logging primitives were removed in v3.x.x. This should be trivial to fix, but feel free to ping me if it isn't.
Additionally, since those patches were authored agaisnt v3.x.x, the documentation mention they are removed. I'm not sure it's worth the trouble of writing "correct" documentation for v2.x.x and then changing it in v3.x.x...

2017-07-03 19:20 UTC, mathias-lang-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +                ILogger.Level.Trace);
Those unittests are already present in the new logger (as well as the method pasted here).

2017-07-04 09:17 UTC, mihails-strasuns-sociomantic approved these changes

2017-07-04 09:58 UTC, mathias-baumann-sociomantic requested changes

2017-07-04 09:58 UTC, mathias-baumann-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +    /***************************************************************************
Shouldn't the functions above here not also be moved one indent to the left?

2017-07-04 09:58 UTC, mathias-baumann-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +
You introduced two blank lines here where as the rest of the functions have a blank-line distance of one.4
Please keep it consistent :)

2017-07-04 10:00 UTC, mathias-baumann-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +    /***************************************************************************
I suppose those are the functions that would be removed later? In that case you can keep it like this I guess :)-

2017-07-04 10:08 UTC, mathias-lang-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +    /***************************************************************************
Correct

2017-07-04 10:14 UTC, mathias-lang-sociomantic commented on src/ocean/util/log/model/ILogger.d
> +
Removed extra line

2017-07-04 10:35 UTC, mathias-baumann-sociomantic approved these changes

2017-07-04 12:13 UTC, merged