Various enhancements of `ocean.meta`
sociomantic-tsunami/ocean pull request #178
Opened 2017-07-07 17:14 UTC by mihails-strasuns-sociomantic

Last week I have been trying to implement system to generate string
representation of types (and `DeepUnqual` based on it). Unfortunately, this
initial goal has proved to be challenging to the point of probably impossible :(
However I did plenty of modifications/enhancements in `ocean.meta` while hacking
it and those are pretty good to go.

2017-07-07 17:15 UTC, mihails-strasuns-sociomantic commented
@mathias-lang-sociomantic you like this version of typedef utilities more as it is pretty close to your original request.

2017-07-10 09:33 UTC, gavin-norman-sociomantic reviewed
Looks fine. This PR adds quite a few duplicates (or near duplicates) of functionality in `ocean.core.Traits`. What's the intention / plan there?

2017-07-10 09:33 UTC, gavin-norman-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +private istring funcIdentifierHack(alias Sym)()
Normal doc would be nice, even if it's private.

2017-07-10 10:34 UTC, mihails-strasuns-sociomantic commented
> What's the intention / plan there?

I am going to eventually deprecate `ocean.core.Traits` in favor of new one but only after trying to switch ocean internals to it and ensuring it works with no nasty surprises. That means several minor releases at least.

2017-07-10 10:42 UTC, gavin-norman-sociomantic commented
>I am going to eventually deprecate ocean.core.Traits in favor of new one but only after trying to switch ocean internals to it and ensuring it works with no nasty surprises. That means several minor releases at least.

Ok. Could you maybe create an issue for this and make a note in the header for `ocean.core.Traits`?

2017-07-10 12:39 UTC, mathias-lang-sociomantic commented on src/ocean/meta/types/ReduceType.d
> +        else static if (isTypedef!(T))
Huge :+1:

2017-07-10 12:40 UTC, mathias-lang-sociomantic commented on relnotes/meta-istring.feature.md
> -  thus simplifying dependency chains.
It's a bit weird to add files after files only to remove them in a later commit... Can't the text just be appended to meta.feature.md ?

2017-07-10 12:42 UTC, mathias-lang-sociomantic commented on src/ocean/meta/AliasSeq.d
> +template AliasSeq (T...)
`/// Ditto` + access qualifier. And `AliasSeq` is extremely ugly, but I will not get into that debate ;)

2017-07-10 12:43 UTC, mathias-lang-sociomantic commented on src/ocean/meta/traits/Basic.d
> +    static assert (staticArrayLength!(int[][5]) == 5);
Could you add UT with other types, for completeness ?

2017-07-10 12:46 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +istring toString ( long i )
We already have https://github.com/sociomantic-tsunami/ocean/blob/bcd88397f484ca4821ceed942b518f05c2e2274f/src/ocean/core/Traits_tango.d#L707-L805 . If you want to move it there, those should be deprecated. Also, why only the signed version is provided ?

2017-07-10 12:46 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (toString(14UL )== "14");
`long.max`, `long.min`, `ulong.max` test cases are needed.

2017-07-10 12:47 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (stripQualifiedPrefix("aabb") == "aabb");
Needing a test case with more than one dot (and a test case with a trailing dot).

2017-07-10 12:49 UTC, mihails-strasuns-sociomantic commented on src/ocean/meta/AliasSeq.d
> +template AliasSeq (T...)
I agree that it is ugly but decided that matching Phobos naming pattern here (and not clashing with `std.typecons.Tuple`) will help us a lot with the learning curve in the long term.

2017-07-10 12:52 UTC, mathias-lang-sociomantic requested changes

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    Template parameter:
`Params`

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    Evaluates to:
Returns

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    static assert (fieldIdentifier!(TestStruct, 1) == "b");
Can you add a test with:

```D
struct Foo { AliasSeq!(int, double, Object) fields; }
```

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    Template_Params:
`Params`

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    if (i==0)
This function really needs spacing

2017-07-10 12:52 UTC, mathias-lang-sociomantic commented on src/ocean/meta/traits/Function.d
> +    static assert (is(Params[2] == char[]));
Can you add a test with a delegate ? What about callable types ?

2017-07-10 12:52 UTC, mihails-strasuns-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +istring toString ( long i )
It is cleaned up copy of those. As I have answered previously to Gavin, intention it to deprecate all symbols in `ocean.core.Traits` in one go when replacement package is sufficiently battle tested, that will be both more reliable and easier migration-wise (one big sed script to run once).

For now only signed long version was copied as I expect other case be of unnecessary complexity in CTFE (How often do you format numbers > long.max in that context?). May copy second overload later.

2017-07-10 13:00 UTC, mathias-lang-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +istring toString ( long i )
Well the `ulong` version is not really hard to implement given your `long` implementation...

2017-07-13 12:01 UTC, mihails-strasuns-sociomantic commented on src/ocean/meta/traits/Function.d
> +    static assert (is(Params[2] == char[]));
Delegate tests added, generic callable types are not supported right now.

2017-07-13 12:03 UTC, mihails-strasuns-sociomantic commented
Updated, should be all @mathias-lang-sociomantic comments addressed.

2017-07-13 12:59 UTC, david-eckardt-sociomantic commented on src/ocean/meta/traits/Function.d
> +    else static if (is( Fn Params == Params* ))
Suggest replacing `Params` with a name that describes what it really is:
- `is( Fn Params == delegate )`: not `Params` but `DgFuncptr`
- `is( Fn Params == Params* )`: not `Params` but `Function`

2017-07-13 13:02 UTC, david-eckardt-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (toString(14UL )== "14");
0 is needed, too.

2017-07-13 13:05 UTC, david-eckardt-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +istring toString ( long i )
Please add a `ulong` version. Even if it's not used very often it's bad to not have it.

2017-07-13 13:09 UTC, david-eckardt-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (stripQualifiedPrefix("aabb") == "aabb");
```d
foreach_reverse (i, c; name)
    if (c == '.')
        return name[i + 1 .. $];

return name;
```
:trollface:

2017-07-13 13:10 UTC, nemanja-boric-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (stripQualifiedPrefix("aabb") == "aabb");
haah

2017-07-13 13:14 UTC, david-eckardt-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    extern(C) void funcNameArgs ( int a, double b ) { }
`static`? Not sure if it makes a difference here, nested `extern(C)` functions are unusual (if at all really possible in the sense that one can call them from an extern C program).

2017-07-16 15:50 UTC, mihails-strasuns-sociomantic commented on src/ocean/meta/codegen/CTFE.d
> +    static assert (stripQualifiedPrefix("aabb") == "aabb");
You rejected a PR that would allow it in a reasonable way so I have no other choice.

2017-07-16 15:51 UTC, mihails-strasuns-sociomantic commented on src/ocean/meta/codegen/Identifier.d
> +    extern(C) void funcNameArgs ( int a, double b ) { }
`static` makes no difference here. `extern(C)` is onlt relevant here because it is reflected in `.stringof` which utility relies on.

2017-07-16 15:53 UTC, mihails-strasuns-sociomantic commented
Updated:
- CTFE `toString` for ulong + more tests
- Better type names inside `ParametersOf`

2017-07-21 11:00 UTC, david-eckardt-sociomantic approved these changes

2017-07-31 15:17 UTC, leandro-lucarella-sociomantic reviewed
Conceptual LGTM (I didn't check the implementations, only gave a quick glance at the commit messages and changelog entries mostly)

2017-08-16 09:34 UTC, merged