VersionArgExt: Print unknown version items
sociomantic-tsunami/ocean pull request #247
Opened 2017-09-13 17:56 UTC by leandro-lucarella-sociomantic

Unknown version items present in the `version_info` are not printed, but
if they exist, is probably because the app author thinks is a valuable
piece of information to the user.

This commit prints any unknown version items found.

Related to https://github.com/sociomantic-tsunami/makd/pull/98.

2017-09-13 18:00 UTC, leandro-lucarella-sociomantic commented
After this is merged, I will like to rebump the version thingy for v4.

My idea is to:

* Change `--version` to just print the version, as most programs do.
* Add a `--version-info` to print the whole 2MiB long version information (maybe changing the format too, probably only treating the `version` key specially, and then just print all the rest of the items sorted by key to simplify things, and using a more multi-line `key=value` format).

One question is if we should leave full or short version for logging. Maybe the full version but in a one-liner version (multi-lines in the log might be weird).

Opinions?

2017-09-13 18:15 UTC, leandro-lucarella-sociomantic commented
Updated to add some tests.

2017-09-13 21:02 UTC, mihails-strasuns-sociomantic commented
Wrong base (next minor release will happen in v3.x.x only)

2017-09-13 21:03 UTC, mihails-strasuns-sociomantic requested changes
LGTM apart from the base thing

2017-09-13 21:04 UTC, mihails-strasuns-sociomantic commented
As for change in major - makes sense, but I'd call it `--build-info` as it is not really about just version anymore.

2017-09-13 22:05 UTC, llucax commented
> Wrong base (next minor release will happen in v3.x.x only)

Shouldn't be v2.x.x removed then?

2017-09-14 08:01 UTC, mihails-strasuns-sociomantic commented
> Shouldn't be v2.x.x removed then?

I will remove after doing last point release for 2.9.x - don't think neptune-release will work if major branch is missing.

Note though that v3.x.x is already default branch on github.

2017-09-14 11:02 UTC, leandro-lucarella-sociomantic commented
Rebased on top of v3.x.x

2017-09-14 11:10 UTC, leandro-lucarella-sociomantic commented
https://travis-ci.org/sociomantic-tsunami/ocean/jobs/275419898#L782

```
  run build/devel/tmp/allunittests

core.exception.AssertError@./src/ocean/task/Task.d(326): Assertion failure
```

Ugh? This really doesn't look related to what I did. Do we have flakey tests? It only failed on `DMD=2.071.2.s1 DIST=xenial F=devel`.

2017-09-14 11:13 UTC, mihails-strasuns-sociomantic commented
Hm, it fires from tests for task timer code so some flakey-ness may be the cause. However this is the first time ever I see it failing in ocean PR so not sure..

2017-09-14 11:20 UTC, leandro-lucarella-sociomantic commented
I could try a re-run and see what happens.

2017-09-14 11:30 UTC, leandro-lucarella-sociomantic commented
FLAKEY

2017-09-14 11:37 UTC, mihails-strasuns-sociomantic commented
Damn :/

2017-09-14 11:44 UTC, leandro-lucarella-sociomantic commented
Ah, release notes are outdated, I'll make a tiny adjustment before merging. Hold on!

2017-09-14 11:46 UTC, leandro-lucarella-sociomantic commented
Updated.

2017-09-15 09:32 UTC, mihails-strasuns-sociomantic approved these changes

2017-09-15 09:32 UTC, merged