Change Template_Params to Params
sociomantic-tsunami/ocean pull request #296
Opened 2017-10-09 14:10 UTC by nemanja-boric-sociomantic

ddoc uses Params both for template and runtime function parameters, but
the existing documentation used `Template_Params` for the template
parameters' documentation. They are now unified under `Params`.

Fixes #282

2017-10-09 15:39 UTC, gavin-norman-sociomantic requested changes
Just one mini point.

2017-10-09 15:39 UTC, gavin-norman-sociomantic commented on src/ocean/core/Traits.d
> +    Params
Missing :

2017-10-10 09:23 UTC, mihails-strasuns-sociomantic approved these changes

2017-10-10 09:45 UTC, nemanja-boric-sociomantic commented on src/ocean/core/Traits.d
> +    Params
Good catch.

2017-10-10 09:46 UTC, nemanja-boric-sociomantic commented
Updated,

2017-10-10 09:47 UTC, gavin-norman-sociomantic approved these changes

2017-10-11 17:20 UTC, leandro-lucarella-sociomantic approved these changes

2017-10-11 17:20 UTC, leandro-lucarella-sociomantic commented
It would be nice to generate the docs somewhere to verify this works :)

2017-10-11 17:20 UTC, merged