Fix duplicate enum definition in Uri module
sociomantic-tsunami/ocean pull request #319
Opened 2017-10-20 14:10 UTC by ben-palmer-sociomantic

The Uri.IncUser and Uri.IncScheme were both set to the same bit mask
value. One was set to 0x80 instead of 0x08.

2017-10-20 14:11 UTC, ben-palmer-sociomantic commented
I did a search in application code for `IncScheme` (https://github.com/search?utf8=%E2%9C%93&q=user%3Asociomantic+IncScheme&type=Code) and `IncUser` (https://github.com/search?utf8=%E2%9C%93&q=user%3Asociomantic+IncUser&type=Code) with no results.

2017-10-20 14:12 UTC, mihails-strasuns-sociomantic requested changes
Looks good but:
1) v3.4.x base
2) some test :)

2017-10-20 14:31 UTC, ben-palmer-sociomantic commented
Rebased and added unit tests.

2017-10-20 14:38 UTC, mihails-strasuns-sociomantic approved these changes

2017-10-20 14:41 UTC, ben-palmer-sociomantic commented
Note that at this stage this looks like it will be required for video ads so is high priority.

2017-10-20 14:54 UTC, mihails-strasuns-sociomantic commented
I aim to release both this and https://github.com/sociomantic-tsunami/ocean/issues/281 on Monday

2017-10-20 14:56 UTC, ben-palmer-sociomantic commented
> I aim to release both this and #281 on Monday

Perfect, thanks!

2017-10-23 08:41 UTC, gavin-norman-sociomantic approved these changes

2017-10-23 08:42 UTC, merged