Add ocean.task.util.Event
sociomantic-tsunami/ocean pull request #73
Opened 2017-04-10 14:00 UTC by mihails-strasuns-sociomantic

I have encountered several cases when having such wrapper would simplify the
code considerably. Typical example is something like swarm `assign` which may or
may not execute immediately - currently everyone adds trigger flag manually but
same pattern can be automated with a simple struct.

2017-04-10 14:02 UTC, nemanja-boric-sociomantic commented
Very cool indeed :+1:

2017-04-10 14:21 UTC, mathias-baumann-sociomantic requested changes
LGTM after squashing my changes

2017-04-10 14:24 UTC, mihails-strasuns-sociomantic commented
Squashed grammar fixes

2017-04-10 15:48 UTC, mathias-baumann-sociomantic approved these changes

2017-04-10 15:48 UTC, mathias-baumann-sociomantic commented
Given that this now also contains my changes, nemanja should have the last word ;)

2017-04-11 08:04 UTC, nemanja-boric-sociomantic approved these changes

2017-04-11 08:04 UTC, merged

2017-04-11 08:50 UTC, gavin-norman-sociomantic commented on relnotes/task-event.feature.md
> +  behaviour of the deprecated `FiberSelectEvent` class, allowing you to
"deprecated" ;)

2017-04-11 08:51 UTC, gavin-norman-sociomantic commented
Nice :+1: