Merge tag 'v4.8.0' into v5.x.x
sociomantic-tsunami/ocean pull request #760
Opened 2019-09-30 14:51 UTC by ben-palmer-sociomantic

2019-09-30 16:21 UTC, Geod24 requested changes

2019-09-30 16:21 UTC, Geod24 commented on src/ocean/text/json/Json.d
> +version (UnitTest)
Wrong

2019-10-01 07:50 UTC, ben-palmer-sociomantic commented on src/ocean/text/json/Json.d
> +version (UnitTest)
Should it stay as `version (unittest)`?

2019-10-01 07:51 UTC, ben-palmer-sociomantic commented
Marking as blocked until I have done the required bug fix to v4.8.x then this should be a simple merge.

2019-10-01 08:34 UTC, Geod24 commented on src/ocean/text/json/Json.d
> +version (UnitTest)
Yes

2019-10-01 15:31 UTC, ben-palmer-sociomantic commented
Closing without merging as not needed.

2019-10-01 15:31 UTC, closed without merging