Rename BitArray.init to BitArray.initialize
sociomantic-tsunami/ocean pull request #782
Opened 2019-11-07 03:25 UTC by AndrejMitrovic

I targeted v6.x.x since this is technically a breaking change. But I don't see this used anywhere right now, at least not in other parts of ocean and swarm. For the closed-source stuff, I don't know. ^_^

Fixes #781

2019-11-08 08:29 UTC, alaksiej-stankievicx-dunnhumby requested changes
Code-wise looks good for me. Also, I have checked our close source code, and glad to inform, that `BitArray.init` is not used.

However, to the merit of consistent transition policy, I suggest  2 separate PR to address issue sociomantic-tsunami/ocean#781. The first one should target v5.x.x branch, introduce new member-function `initialize`, which should be called inside the old `init`, and dperecate `init` member-function. The second one should target v6.x.x and remove dprecated `init`.

2019-11-08 08:52 UTC, AndrejMitrovic commented
Sure thing, I'll update it on the weekend. Thanks @alaksiej-stankievicx-sociomantic!

2019-11-12 06:50 UTC, AndrejMitrovic commented
Once https://github.com/sociomantic-tsunami/ocean/pull/784 is merged and v5.x.x is merged into v6.x.x, I'll update this PR.

2019-11-19 00:52 UTC, AndrejMitrovic commented
Hey guys, any update on merging v5.x.x to v6.x.x? :)

2019-11-19 09:39 UTC, alaksiej-stankievicx-sociomantic commented
Hey! We have discussed this @ben-palmer-sociomantic. It seems we have almost enough changes for new minor release in v5.x.x, so we want to merge v5.x.x to v6.x.x after that release. However, we have two PR request from Joseph Wakeling, which good to have, but they don't have unittests. So by the end of the week I will patch this PRs with unittests, and we aiming to have next release at the begin of the next week.

2019-11-20 00:54 UTC, AndrejMitrovic commented
Alright, thanks a lot!

2019-11-26 17:05 UTC, ben-palmer-sociomantic commented
I have updated the v6.x.x branch with the latest release from v5.x.x now

2019-11-27 00:25 UTC, AndrejMitrovic commented
Thanks Ben! Updated the PR.

2019-11-28 10:30 UTC, alaksiej-stankievicx-dunnhumby approved these changes
LGTM

2019-12-18 09:54 UTC, ben-palmer-sociomantic approved these changes
LGTM

2019-12-18 09:54 UTC, merged